[package]
name = "snarkos"
version = "2.0.2"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "A decentralized operating system"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkOS"
keywords = [
    "aleo",
    "cryptography",
    "blockchain",
    "decentralized",
    "zero-knowledge"
]
categories = [ "cryptography", "operating-systems" ]
license = "GPL-3.0"
edition = "2021"

[workspace]
members = [
    "account",
    "cli",
    "display",
    "node",
    "node/cdn",
    "node/consensus",
    "node/bft-consensus",
    "node/ledger",
    "node/messages",
    "node/metrics",
    "node/rest",
    "node/router",
    "node/store",
    "node/tcp",
    ".integration",
]

[[bin]]
name = "snarkos"
path = "snarkos/main.rs"

[workspace.dependencies]
narwhal-types       = { git = "https://github.com/eqlabs/bullshark-bft/", branch = "feat/metrics", package = "narwhal-types" }
narwhal-config      = { git = "https://github.com/eqlabs/bullshark-bft/", branch = "feat/metrics", package = "narwhal-config" }
narwhal-crypto      = { git = "https://github.com/eqlabs/bullshark-bft/", branch = "feat/metrics", package = "narwhal-crypto" }
narwhal-executor    = { git = "https://github.com/eqlabs/bullshark-bft/", branch = "feat/metrics", package = "narwhal-executor" }
narwhal-node        = { git = "https://github.com/eqlabs/bullshark-bft/", branch = "feat/metrics", package = "narwhal-node"}
narwhal-worker      = { git = "https://github.com/eqlabs/bullshark-bft/", branch = "feat/metrics", package = "narwhal-worker"}

[workspace.dependencies.snarkvm]
#path = "../snarkVM"
#git = "https://github.com/AleoHQ/snarkVM.git"
version = "=0.10.2"
features = ["circuit", "console"]

[dependencies.anyhow]
version = "1.0.70"

[dependencies.clap]
version = "3.2"
features = ["derive"]

[dependencies.snarkos-account]
path = "./account"

[dependencies.snarkos-cli]
path = "./cli"

[dependencies.snarkos-display]
path = "./display"

[dependencies.snarkos-node]
path = "./node"

[dependencies.snarkos-node-cdn]
path = "./node/cdn"

[dependencies.snarkos-node-consensus]
path = "./node/consensus"

[dependencies.snarkos-node-ledger]
path = "./node/ledger"

[dependencies.snarkos-node-messages]
path = "./node/messages"

[dependencies.snarkos-node-rest]
path = "./node/rest"

[dependencies.snarkos-node-router]
path = "./node/router"

[dependencies.snarkos-node-store]
path = "./node/store"

[dependencies.snarkos-node-tcp]
path = "./node/tcp"

[dependencies.tikv-jemallocator]
version = "0.5"

[dev-dependencies.rusty-hook]
version = "0.11.2"

[build-dependencies.walkdir]
version = "2"

[profile.release]
opt-level = 3
lto = "thin"
incremental = true

[profile.bench]
opt-level = 3
debug = false
rpath = false
lto = "thin"
incremental = true
debug-assertions = false

[profile.dev]
opt-level = 2
lto = "thin"
incremental = true

[profile.test]
opt-level = 2
lto = "thin"
incremental = true
debug = true
debug-assertions = true
