[package]
name = "snarkos-tx-generator"
version = "2.0.2"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "A decentralized operating system"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkOS"
keywords = [
    "aleo",
    "cryptography",
    "blockchain",
    "decentralized",
    "zero-knowledge"
]
categories = [ "cryptography", "operating-systems" ]
license = "GPL-3.0"
edition = "2021"

[[bin]]
name = "tx_generator"
path = "src/main.rs"

[dependencies.anyhow]
version = "1.0.70"

[dependencies.indexmap]
version = "1.9"
features = [ "rayon" ]

[dependencies.once_cell]
version = "1.13"

[dependencies.parking_lot]
version = "0.12"

[dependencies.rand]
version = "0.8"

[dependencies.rand_chacha]
version = "0.3.0"
default-features = false

[dependencies.rayon]
version = "1"
optional = true

[dependencies.snarkvm]
workspace = true

[dependencies.time]
version = "0.3"

[dependencies.tracing]
version = "0.1"

[dependencies.bytes]
version = "1"

[dependencies.itertools]
version = "0.10"

[dependencies.multiaddr]
version = "0.17"

[dependencies.narwhal-config]
workspace = true

[dependencies.narwhal-types]
workspace = true

[dependencies.snarkos-account]
path = "../account"

[dependencies.snarkos-node]
path = "../node"
features = ["test"]

[dependencies.snarkos-node-consensus]
path = "../node/consensus"

[dependencies.snarkos-node-messages]
path = "../node/messages"

[dependencies.tikv-jemallocator]
version = "0.5"

[dependencies.tokio]
version = "1"
features = ["macros", "rt-multi-thread"]

[dependencies.tonic]
version = "0.8"

[dependencies.tracing-subscriber]
version = "0.3"

[dependencies.tracing-test]
version = "0.2"

# a workaround to use the `test` feature in tests by default
[dependencies.snarkos-node-bft-consensus]
path = "../node/bft-consensus"
features = ["test"]
